### ISSUE TITLE
Registry overview pages needs updating

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-venafi#414]
### Describe what happened

The [Venafi Overview page](https://www.pulumi.com/registry/packages/venafi/) and [Install and Config page](https://www.pulumi.com/registry/packages/venafi/installation-configuration/) have diverged significantly from [the TF Registry docs](https://registry.terraform.io/providers/Venafi/venafi/latest/docs).

Specific stuff I noticed:

- There's example code on the Overview that belongs in the Certificate resource page (which has no examples).
- Installation parameters are missing. (I think @iwahbe automated generating these docs in a recent demo.)

### Sample program

n/a

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @jkodroff. I'm pretty sure that demo was from @guineveresaenger, since she's been working on automating this.
