### ISSUE TITLE
Acceptance tests failing

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-venafi#47]
Acceptance test `TestCertificateTs` is failing with a 500 returned from the Venafi API. Filed https://github.com/Venafi/terraform-provider-venafi/issues/72 to make sure they are aware.

It's possible that updating the upstream provider will fix the issue, but guessing this is unlikely assuming the 500 is the semantically appropriate response, because a 500 indicates a programming error in the API itself.

**Comment by jkisk** [comment]
Yep, this seems to have resolved upstream!
